// Code generated by Kitex v0.15.4. DO NOT EDIT.

package paymentsvr

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

type Client interface {
	ProcessPayment(ctx context.Context, orderId string, userId string, callOptions ...callopt.Option) (r bool, err error)
}

func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kPaymentSvrClient{
		kClient: newServiceClient(kc),
	}, nil
}

func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPaymentSvrClient struct {
	*kClient
}

func (p *kPaymentSvrClient) ProcessPayment(ctx context.Context, orderId string, userId string, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ProcessPayment(ctx, orderId, userId)
}
