// Code generated by Kitex v0.15.4. DO NOT EDIT.

package paymentsvr

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	paymentsvr "seckill/internal/paymentSvr/kitex_gen/paymentsvr"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ProcessPayment": kitex.NewMethodInfo(
		processPaymentHandler,
		newPaymentSvrProcessPaymentArgs,
		newPaymentSvrProcessPaymentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	paymentSvrServiceInfo                = NewServiceInfo()
	paymentSvrServiceInfoForClient       = NewServiceInfoForClient()
	paymentSvrServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

func serviceInfo() *kitex.ServiceInfo {
	return paymentSvrServiceInfo
}

func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return paymentSvrServiceInfoForStreamClient
}

func serviceInfoForClient() *kitex.ServiceInfo {
	return paymentSvrServiceInfoForClient
}

func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}

func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PaymentSvr"
	handlerType := (*paymentsvr.PaymentSvr)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "paymentsvr",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func processPaymentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*paymentsvr.PaymentSvrProcessPaymentArgs)
	realResult := result.(*paymentsvr.PaymentSvrProcessPaymentResult)
	success, err := handler.(paymentsvr.PaymentSvr).ProcessPayment(ctx, realArg.OrderId, realArg.UserId)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}

func newPaymentSvrProcessPaymentArgs() interface{} {
	return paymentsvr.NewPaymentSvrProcessPaymentArgs()
}

func newPaymentSvrProcessPaymentResult() interface{} {
	return paymentsvr.NewPaymentSvrProcessPaymentResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ProcessPayment(ctx context.Context, orderId string, userId string) (r bool, err error) {
	var _args paymentsvr.PaymentSvrProcessPaymentArgs
	_args.OrderId = orderId
	_args.UserId = userId
	var _result paymentsvr.PaymentSvrProcessPaymentResult
	if err = p.c.Call(ctx, "ProcessPayment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
