// Code generated by Kitex v0.15.4. DO NOT EDIT.
package paymentsvr

import (
	server "github.com/cloudwego/kitex/server"
	paymentsvr "seckill/internal/paymentSvr/kitex_gen/paymentsvr"
)

func NewServer(handler paymentsvr.PaymentSvr, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler paymentsvr.PaymentSvr, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
