// Code generated by Kitex v0.15.4. DO NOT EDIT.

package ordersvr

import (
	"context"
	ordersvr "seckill/internal/orderSvr/kitex_gen/ordersvr"

	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

type Client interface {
	CreateOrder(ctx context.Context, userId string, itemId string, price float64, callOptions ...callopt.Option) (r string, err error)
	QueryPaidOrders(ctx context.Context, userId string, callOptions ...callopt.Option) (r []*ordersvr.OrderInfo, err error)
	QueryUnpaidOrders(ctx context.Context, userId string, callOptions ...callopt.Option) (r []*ordersvr.OrderInfo, err error)
	QueryCancelledOrders(ctx context.Context, userId string, callOptions ...callopt.Option) (r []*ordersvr.OrderInfo, err error)
}

func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kOrderSvrClient{
		kClient: newServiceClient(kc),
	}, nil
}

func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kOrderSvrClient struct {
	*kClient
}

func (p *kOrderSvrClient) CreateOrder(ctx context.Context, userId string, itemId string, price float64, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOrder(ctx, userId, itemId, price)
}

func (p *kOrderSvrClient) QueryPaidOrders(ctx context.Context, userId string, callOptions ...callopt.Option) (r []*ordersvr.OrderInfo, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryPaidOrders(ctx, userId)
}

func (p *kOrderSvrClient) QueryUnpaidOrders(ctx context.Context, userId string, callOptions ...callopt.Option) (r []*ordersvr.OrderInfo, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryUnpaidOrders(ctx, userId)
}

func (p *kOrderSvrClient) QueryCancelledOrders(ctx context.Context, userId string, callOptions ...callopt.Option) (r []*ordersvr.OrderInfo, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryCancelledOrders(ctx, userId)
}
