// Code generated by Kitex v0.15.4. DO NOT EDIT.

package ordersvr

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	ordersvr "seckill/internal/orderSvr/kitex_gen/ordersvr"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateOrder": kitex.NewMethodInfo(
		createOrderHandler,
		newOrderSvrCreateOrderArgs,
		newOrderSvrCreateOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryPaidOrders": kitex.NewMethodInfo(
		queryPaidOrdersHandler,
		newOrderSvrQueryPaidOrdersArgs,
		newOrderSvrQueryPaidOrdersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryUnpaidOrders": kitex.NewMethodInfo(
		queryUnpaidOrdersHandler,
		newOrderSvrQueryUnpaidOrdersArgs,
		newOrderSvrQueryUnpaidOrdersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryCancelledOrders": kitex.NewMethodInfo(
		queryCancelledOrdersHandler,
		newOrderSvrQueryCancelledOrdersArgs,
		newOrderSvrQueryCancelledOrdersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	orderSvrServiceInfo                = NewServiceInfo()
	orderSvrServiceInfoForClient       = NewServiceInfoForClient()
	orderSvrServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

func serviceInfo() *kitex.ServiceInfo {
	return orderSvrServiceInfo
}

func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return orderSvrServiceInfoForStreamClient
}

func serviceInfoForClient() *kitex.ServiceInfo {
	return orderSvrServiceInfoForClient
}

func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}

func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "OrderSvr"
	handlerType := (*ordersvr.OrderSvr)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "ordersvr",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func createOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ordersvr.OrderSvrCreateOrderArgs)
	realResult := result.(*ordersvr.OrderSvrCreateOrderResult)
	success, err := handler.(ordersvr.OrderSvr).CreateOrder(ctx, realArg.UserId, realArg.ItemId, realArg.Price)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}

func newOrderSvrCreateOrderArgs() interface{} {
	return ordersvr.NewOrderSvrCreateOrderArgs()
}

func newOrderSvrCreateOrderResult() interface{} {
	return ordersvr.NewOrderSvrCreateOrderResult()
}

func queryPaidOrdersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ordersvr.OrderSvrQueryPaidOrdersArgs)
	realResult := result.(*ordersvr.OrderSvrQueryPaidOrdersResult)
	success, err := handler.(ordersvr.OrderSvr).QueryPaidOrders(ctx, realArg.UserId)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newOrderSvrQueryPaidOrdersArgs() interface{} {
	return ordersvr.NewOrderSvrQueryPaidOrdersArgs()
}

func newOrderSvrQueryPaidOrdersResult() interface{} {
	return ordersvr.NewOrderSvrQueryPaidOrdersResult()
}

func queryUnpaidOrdersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ordersvr.OrderSvrQueryUnpaidOrdersArgs)
	realResult := result.(*ordersvr.OrderSvrQueryUnpaidOrdersResult)
	success, err := handler.(ordersvr.OrderSvr).QueryUnpaidOrders(ctx, realArg.UserId)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newOrderSvrQueryUnpaidOrdersArgs() interface{} {
	return ordersvr.NewOrderSvrQueryUnpaidOrdersArgs()
}

func newOrderSvrQueryUnpaidOrdersResult() interface{} {
	return ordersvr.NewOrderSvrQueryUnpaidOrdersResult()
}

func queryCancelledOrdersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ordersvr.OrderSvrQueryCancelledOrdersArgs)
	realResult := result.(*ordersvr.OrderSvrQueryCancelledOrdersResult)
	success, err := handler.(ordersvr.OrderSvr).QueryCancelledOrders(ctx, realArg.UserId)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newOrderSvrQueryCancelledOrdersArgs() interface{} {
	return ordersvr.NewOrderSvrQueryCancelledOrdersArgs()
}

func newOrderSvrQueryCancelledOrdersResult() interface{} {
	return ordersvr.NewOrderSvrQueryCancelledOrdersResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateOrder(ctx context.Context, userId string, itemId string, price float64) (r string, err error) {
	var _args ordersvr.OrderSvrCreateOrderArgs
	_args.UserId = userId
	_args.ItemId = itemId
	_args.Price = price
	var _result ordersvr.OrderSvrCreateOrderResult
	if err = p.c.Call(ctx, "CreateOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryPaidOrders(ctx context.Context, userId string) (r []*ordersvr.OrderInfo, err error) {
	var _args ordersvr.OrderSvrQueryPaidOrdersArgs
	_args.UserId = userId
	var _result ordersvr.OrderSvrQueryPaidOrdersResult
	if err = p.c.Call(ctx, "QueryPaidOrders", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryUnpaidOrders(ctx context.Context, userId string) (r []*ordersvr.OrderInfo, err error) {
	var _args ordersvr.OrderSvrQueryUnpaidOrdersArgs
	_args.UserId = userId
	var _result ordersvr.OrderSvrQueryUnpaidOrdersResult
	if err = p.c.Call(ctx, "QueryUnpaidOrders", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryCancelledOrders(ctx context.Context, userId string) (r []*ordersvr.OrderInfo, err error) {
	var _args ordersvr.OrderSvrQueryCancelledOrdersArgs
	_args.UserId = userId
	var _result ordersvr.OrderSvrQueryCancelledOrdersResult
	if err = p.c.Call(ctx, "QueryCancelledOrders", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
