// Code generated by Kitex v0.15.4. DO NOT EDIT.
package ordersvr

import (
	server "github.com/cloudwego/kitex/server"
	ordersvr "seckill/internal/orderSvr/kitex_gen/ordersvr"
)

func NewServer(handler ordersvr.OrderSvr, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler ordersvr.OrderSvr, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
