// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package paymentsvr

import (
	"context"
	"fmt"
)

type PaymentSvr interface {
	ProcessPayment(ctx context.Context, orderId string, userId string) (r bool, err error)
}

type PaymentSvrProcessPaymentArgs struct {
	OrderId string `thrift:"orderId,1" frugal:"1,default,string" json:"orderId"`
	UserId  string `thrift:"userId,2" frugal:"2,default,string" json:"userId"`
}

func NewPaymentSvrProcessPaymentArgs() *PaymentSvrProcessPaymentArgs {
	return &PaymentSvrProcessPaymentArgs{}
}

func (p *PaymentSvrProcessPaymentArgs) InitDefault() {
}

func (p *PaymentSvrProcessPaymentArgs) GetOrderId() (v string) {
	return p.OrderId
}

func (p *PaymentSvrProcessPaymentArgs) GetUserId() (v string) {
	return p.UserId
}

func (p *PaymentSvrProcessPaymentArgs) SetOrderId(val string) {
	p.OrderId = val
}

func (p *PaymentSvrProcessPaymentArgs) SetUserId(val string) {
	p.UserId = val
}

func (p *PaymentSvrProcessPaymentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentSvrProcessPaymentArgs(%+v)", *p)
}

var fieldIDToName_PaymentSvrProcessPaymentArgs = map[int16]string{
	1: "orderId",
	2: "userId",
}

type PaymentSvrProcessPaymentResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewPaymentSvrProcessPaymentResult() *PaymentSvrProcessPaymentResult {
	return &PaymentSvrProcessPaymentResult{}
}

func (p *PaymentSvrProcessPaymentResult) InitDefault() {
}

var PaymentSvrProcessPaymentResult_Success_DEFAULT bool

func (p *PaymentSvrProcessPaymentResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return PaymentSvrProcessPaymentResult_Success_DEFAULT
	}
	return *p.Success
}

func (p *PaymentSvrProcessPaymentResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *PaymentSvrProcessPaymentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PaymentSvrProcessPaymentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentSvrProcessPaymentResult(%+v)", *p)
}

var fieldIDToName_PaymentSvrProcessPaymentResult = map[int16]string{
	0: "success",
}
