// Code generated by Kitex v0.15.4. DO NOT EDIT.

package itemsvr

import (
	"context"
	itemsvr "seckill/internal/itemSvr/kitex_gen/itemsvr"

	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

type Client interface {
	AddItem(ctx context.Context, name string, stock int64, price float64, description string, callOptions ...callopt.Option) (r string, err error)
	DeleteItem(ctx context.Context, id string, callOptions ...callopt.Option) (err error)
	StartFlashSale(ctx context.Context, itemId string, callOptions ...callopt.Option) (err error)
	StopFlashSale(ctx context.Context, itemId string, callOptions ...callopt.Option) (err error)
	ListItems(ctx context.Context, uid string, role string, callOptions ...callopt.Option) (r []*itemsvr.ItemInfo, err error)
	GetItem(ctx context.Context, itemId string, callOptions ...callopt.Option) (r *itemsvr.ItemInfo, err error)
	PrepareOrder(ctx context.Context, userId string, itemId string, callOptions ...callopt.Option) (r float64, err error)
}

func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kItemSvrClient{
		kClient: newServiceClient(kc),
	}, nil
}

func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kItemSvrClient struct {
	*kClient
}

func (p *kItemSvrClient) AddItem(ctx context.Context, name string, stock int64, price float64, description string, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddItem(ctx, name, stock, price, description)
}

func (p *kItemSvrClient) DeleteItem(ctx context.Context, id string, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteItem(ctx, id)
}

func (p *kItemSvrClient) StartFlashSale(ctx context.Context, itemId string, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StartFlashSale(ctx, itemId)
}

func (p *kItemSvrClient) StopFlashSale(ctx context.Context, itemId string, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StopFlashSale(ctx, itemId)
}

func (p *kItemSvrClient) ListItems(ctx context.Context, uid string, role string, callOptions ...callopt.Option) (r []*itemsvr.ItemInfo, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListItems(ctx, uid, role)
}

func (p *kItemSvrClient) GetItem(ctx context.Context, itemId string, callOptions ...callopt.Option) (r *itemsvr.ItemInfo, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetItem(ctx, itemId)
}

func (p *kItemSvrClient) PrepareOrder(ctx context.Context, userId string, itemId string, callOptions ...callopt.Option) (r float64, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PrepareOrder(ctx, userId, itemId)
}
