// Code generated by Kitex v0.15.4. DO NOT EDIT.

package itemsvr

import (
	"context"
	"errors"
	itemsvr "seckill/internal/itemSvr/kitex_gen/itemsvr"

	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"AddItem": kitex.NewMethodInfo(
		addItemHandler,
		newItemSvrAddItemArgs,
		newItemSvrAddItemResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteItem": kitex.NewMethodInfo(
		deleteItemHandler,
		newItemSvrDeleteItemArgs,
		newItemSvrDeleteItemResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"StartFlashSale": kitex.NewMethodInfo(
		startFlashSaleHandler,
		newItemSvrStartFlashSaleArgs,
		newItemSvrStartFlashSaleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"StopFlashSale": kitex.NewMethodInfo(
		stopFlashSaleHandler,
		newItemSvrStopFlashSaleArgs,
		newItemSvrStopFlashSaleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListItems": kitex.NewMethodInfo(
		listItemsHandler,
		newItemSvrListItemsArgs,
		newItemSvrListItemsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	itemSvrServiceInfo                = NewServiceInfo()
	itemSvrServiceInfoForClient       = NewServiceInfoForClient()
	itemSvrServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

func serviceInfo() *kitex.ServiceInfo {
	return itemSvrServiceInfo
}

func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return itemSvrServiceInfoForStreamClient
}

func serviceInfoForClient() *kitex.ServiceInfo {
	return itemSvrServiceInfoForClient
}

func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}

func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ItemSvr"
	handlerType := (*itemsvr.ItemSvr)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "itemsvr",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func addItemHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*itemsvr.ItemSvrAddItemArgs)
	realResult := result.(*itemsvr.ItemSvrAddItemResult)
	success, err := handler.(itemsvr.ItemSvr).AddItem(ctx, realArg.Name, realArg.Stock, realArg.Price, realArg.Description)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}

func newItemSvrAddItemArgs() interface{} {
	return itemsvr.NewItemSvrAddItemArgs()
}

func newItemSvrAddItemResult() interface{} {
	return itemsvr.NewItemSvrAddItemResult()
}

func deleteItemHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*itemsvr.ItemSvrDeleteItemArgs)

	err := handler.(itemsvr.ItemSvr).DeleteItem(ctx, realArg.ID)
	if err != nil {
		return err
	}

	return nil
}

func newItemSvrDeleteItemArgs() interface{} {
	return itemsvr.NewItemSvrDeleteItemArgs()
}

func newItemSvrDeleteItemResult() interface{} {
	return itemsvr.NewItemSvrDeleteItemResult()
}

func startFlashSaleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*itemsvr.ItemSvrStartFlashSaleArgs)

	err := handler.(itemsvr.ItemSvr).StartFlashSale(ctx, realArg.ItemId)
	if err != nil {
		return err
	}

	return nil
}

func newItemSvrStartFlashSaleArgs() interface{} {
	return itemsvr.NewItemSvrStartFlashSaleArgs()
}

func newItemSvrStartFlashSaleResult() interface{} {
	return itemsvr.NewItemSvrStartFlashSaleResult()
}

func stopFlashSaleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*itemsvr.ItemSvrStopFlashSaleArgs)

	err := handler.(itemsvr.ItemSvr).StopFlashSale(ctx, realArg.ItemId)
	if err != nil {
		return err
	}

	return nil
}

func newItemSvrStopFlashSaleArgs() interface{} {
	return itemsvr.NewItemSvrStopFlashSaleArgs()
}

func newItemSvrStopFlashSaleResult() interface{} {
	return itemsvr.NewItemSvrStopFlashSaleResult()
}

func listItemsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*itemsvr.ItemSvrListItemsArgs)
	realResult := result.(*itemsvr.ItemSvrListItemsResult)
	success, err := handler.(itemsvr.ItemSvr).ListItems(ctx, realArg.Uid, realArg.Role)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newItemSvrListItemsArgs() interface{} {
	return itemsvr.NewItemSvrListItemsArgs()
}

func newItemSvrListItemsResult() interface{} {
	return itemsvr.NewItemSvrListItemsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) AddItem(ctx context.Context, name string, stock int64, price float64, description string) (r string, err error) {
	var _args itemsvr.ItemSvrAddItemArgs
	_args.Name = name
	_args.Stock = stock
	_args.Price = price
	_args.Description = description
	var _result itemsvr.ItemSvrAddItemResult
	if err = p.c.Call(ctx, "AddItem", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteItem(ctx context.Context, id string) (err error) {
	var _args itemsvr.ItemSvrDeleteItemArgs
	_args.ID = id
	var _result itemsvr.ItemSvrDeleteItemResult
	if err = p.c.Call(ctx, "DeleteItem", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) StartFlashSale(ctx context.Context, itemId string) (err error) {
	var _args itemsvr.ItemSvrStartFlashSaleArgs
	_args.ItemId = itemId
	var _result itemsvr.ItemSvrStartFlashSaleResult
	if err = p.c.Call(ctx, "StartFlashSale", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) StopFlashSale(ctx context.Context, itemId string) (err error) {
	var _args itemsvr.ItemSvrStopFlashSaleArgs
	_args.ItemId = itemId
	var _result itemsvr.ItemSvrStopFlashSaleResult
	if err = p.c.Call(ctx, "StopFlashSale", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) ListItems(ctx context.Context, uid string, role string) (r []*itemsvr.ItemInfo, err error) {
	var _args itemsvr.ItemSvrListItemsArgs
	_args.Uid = uid
	_args.Role = role
	var _result itemsvr.ItemSvrListItemsResult
	if err = p.c.Call(ctx, "ListItems", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
