// Code generated by Kitex v0.15.4. DO NOT EDIT.
package itemsvr

import (
	server "github.com/cloudwego/kitex/server"
	itemsvr "seckill/internal/itemSvr/kitex_gen/itemsvr"
)

func NewServer(handler itemsvr.ItemSvr, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler itemsvr.ItemSvr, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
