// Code generated by Kitex v0.15.4. DO NOT EDIT.

package usersvr

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	usersvr "seckill/internal/userSvr/kitex_gen/usersvr"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	RegisterUser(ctx context.Context, uid string, password string, callOptions ...callopt.Option) (err error)
	Login(ctx context.Context, uid string, password string, callOptions ...callopt.Option) (r *usersvr.JWTToken, err error)
	Logout(ctx context.Context, accessToken string, callOptions ...callopt.Option) (err error)
	RefreshAccessToken(ctx context.Context, refreshToken string, callOptions ...callopt.Option) (r string, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserSvrClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserSvrClient struct {
	*kClient
}

func (p *kUserSvrClient) RegisterUser(ctx context.Context, uid string, password string, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RegisterUser(ctx, uid, password)
}

func (p *kUserSvrClient) Login(ctx context.Context, uid string, password string, callOptions ...callopt.Option) (r *usersvr.JWTToken, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, uid, password)
}

func (p *kUserSvrClient) Logout(ctx context.Context, accessToken string, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Logout(ctx, accessToken)
}

func (p *kUserSvrClient) RefreshAccessToken(ctx context.Context, refreshToken string, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefreshAccessToken(ctx, refreshToken)
}
