// Code generated by Kitex v0.15.4. DO NOT EDIT.

package usersvr

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	usersvr "seckill/internal/userSvr/kitex_gen/usersvr"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"RegisterUser": kitex.NewMethodInfo(
		registerUserHandler,
		newUserSvrRegisterUserArgs,
		newUserSvrRegisterUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newUserSvrLoginArgs,
		newUserSvrLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Logout": kitex.NewMethodInfo(
		logoutHandler,
		newUserSvrLogoutArgs,
		newUserSvrLogoutResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RefreshAccessToken": kitex.NewMethodInfo(
		refreshAccessTokenHandler,
		newUserSvrRefreshAccessTokenArgs,
		newUserSvrRefreshAccessTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"VerifyAccessToken": kitex.NewMethodInfo(
		verifyAccessTokenHandler,
		newUserSvrVerifyAccessTokenArgs,
		newUserSvrVerifyAccessTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"VerifyRefreshToken": kitex.NewMethodInfo(
		verifyRefreshTokenHandler,
		newUserSvrVerifyRefreshTokenArgs,
		newUserSvrVerifyRefreshTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userSvrServiceInfo                = NewServiceInfo()
	userSvrServiceInfoForClient       = NewServiceInfoForClient()
	userSvrServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userSvrServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userSvrServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userSvrServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserSvr"
	handlerType := (*usersvr.UserSvr)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "usersvr",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func registerUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*usersvr.UserSvrRegisterUserArgs)

	err := handler.(usersvr.UserSvr).RegisterUser(ctx, realArg.Email, realArg.Password)
	if err != nil {
		return err
	}

	return nil
}
func newUserSvrRegisterUserArgs() interface{} {
	return usersvr.NewUserSvrRegisterUserArgs()
}

func newUserSvrRegisterUserResult() interface{} {
	return usersvr.NewUserSvrRegisterUserResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*usersvr.UserSvrLoginArgs)
	realResult := result.(*usersvr.UserSvrLoginResult)
	success, err := handler.(usersvr.UserSvr).Login(ctx, realArg.Email, realArg.Password)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserSvrLoginArgs() interface{} {
	return usersvr.NewUserSvrLoginArgs()
}

func newUserSvrLoginResult() interface{} {
	return usersvr.NewUserSvrLoginResult()
}

func logoutHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*usersvr.UserSvrLogoutArgs)

	err := handler.(usersvr.UserSvr).Logout(ctx, realArg.Uid)
	if err != nil {
		return err
	}

	return nil
}
func newUserSvrLogoutArgs() interface{} {
	return usersvr.NewUserSvrLogoutArgs()
}

func newUserSvrLogoutResult() interface{} {
	return usersvr.NewUserSvrLogoutResult()
}

func refreshAccessTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*usersvr.UserSvrRefreshAccessTokenArgs)
	realResult := result.(*usersvr.UserSvrRefreshAccessTokenResult)
	success, err := handler.(usersvr.UserSvr).RefreshAccessToken(ctx, realArg.Claims)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserSvrRefreshAccessTokenArgs() interface{} {
	return usersvr.NewUserSvrRefreshAccessTokenArgs()
}

func newUserSvrRefreshAccessTokenResult() interface{} {
	return usersvr.NewUserSvrRefreshAccessTokenResult()
}

func verifyAccessTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*usersvr.UserSvrVerifyAccessTokenArgs)
	realResult := result.(*usersvr.UserSvrVerifyAccessTokenResult)
	success, err := handler.(usersvr.UserSvr).VerifyAccessToken(ctx, realArg.AccessToken)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserSvrVerifyAccessTokenArgs() interface{} {
	return usersvr.NewUserSvrVerifyAccessTokenArgs()
}

func newUserSvrVerifyAccessTokenResult() interface{} {
	return usersvr.NewUserSvrVerifyAccessTokenResult()
}

func verifyRefreshTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*usersvr.UserSvrVerifyRefreshTokenArgs)
	realResult := result.(*usersvr.UserSvrVerifyRefreshTokenResult)
	success, err := handler.(usersvr.UserSvr).VerifyRefreshToken(ctx, realArg.RefreshToken)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserSvrVerifyRefreshTokenArgs() interface{} {
	return usersvr.NewUserSvrVerifyRefreshTokenArgs()
}

func newUserSvrVerifyRefreshTokenResult() interface{} {
	return usersvr.NewUserSvrVerifyRefreshTokenResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) RegisterUser(ctx context.Context, email string, password string) (err error) {
	var _args usersvr.UserSvrRegisterUserArgs
	_args.Email = email
	_args.Password = password
	var _result usersvr.UserSvrRegisterUserResult
	if err = p.c.Call(ctx, "RegisterUser", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) Login(ctx context.Context, email string, password string) (r *usersvr.JWTToken, err error) {
	var _args usersvr.UserSvrLoginArgs
	_args.Email = email
	_args.Password = password
	var _result usersvr.UserSvrLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Logout(ctx context.Context, uid string) (err error) {
	var _args usersvr.UserSvrLogoutArgs
	_args.Uid = uid
	var _result usersvr.UserSvrLogoutResult
	if err = p.c.Call(ctx, "Logout", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) RefreshAccessToken(ctx context.Context, claims *usersvr.JWTClaims) (r string, err error) {
	var _args usersvr.UserSvrRefreshAccessTokenArgs
	_args.Claims = claims
	var _result usersvr.UserSvrRefreshAccessTokenResult
	if err = p.c.Call(ctx, "RefreshAccessToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifyAccessToken(ctx context.Context, accessToken string) (r *usersvr.JWTClaims, err error) {
	var _args usersvr.UserSvrVerifyAccessTokenArgs
	_args.AccessToken = accessToken
	var _result usersvr.UserSvrVerifyAccessTokenResult
	if err = p.c.Call(ctx, "VerifyAccessToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifyRefreshToken(ctx context.Context, refreshToken string) (r *usersvr.JWTClaims, err error) {
	var _args usersvr.UserSvrVerifyRefreshTokenArgs
	_args.RefreshToken = refreshToken
	var _result usersvr.UserSvrVerifyRefreshTokenResult
	if err = p.c.Call(ctx, "VerifyRefreshToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
