// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package itemsvr

import (
	"context"
	"fmt"
)

type ItemInfo struct {
	ID          string  `thrift:"id,1,required" frugal:"1,required,string" json:"id"`
	Name        string  `thrift:"name,2,required" frugal:"2,required,string" json:"name"`
	Stock       int64   `thrift:"stock,3,required" frugal:"3,required,i64" json:"stock"`
	Price       float64 `thrift:"price,4,required" frugal:"4,required,double" json:"price"`
	Description string  `thrift:"description,5,required" frugal:"5,required,string" json:"description"`
}

func NewItemInfo() *ItemInfo {
	return &ItemInfo{}
}

func (p *ItemInfo) InitDefault() {
}

func (p *ItemInfo) GetID() (v string) {
	return p.ID
}

func (p *ItemInfo) GetName() (v string) {
	return p.Name
}

func (p *ItemInfo) GetStock() (v int64) {
	return p.Stock
}

func (p *ItemInfo) GetPrice() (v float64) {
	return p.Price
}

func (p *ItemInfo) GetDescription() (v string) {
	return p.Description
}

func (p *ItemInfo) SetID(val string) {
	p.ID = val
}

func (p *ItemInfo) SetName(val string) {
	p.Name = val
}

func (p *ItemInfo) SetStock(val int64) {
	p.Stock = val
}

func (p *ItemInfo) SetPrice(val float64) {
	p.Price = val
}

func (p *ItemInfo) SetDescription(val string) {
	p.Description = val
}

func (p *ItemInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemInfo(%+v)", *p)
}

var fieldIDToName_ItemInfo = map[int16]string{
	1: "id",
	2: "name",
	3: "stock",
	4: "price",
	5: "description",
}

type ItemSvr interface {
	AddItem(ctx context.Context, name string, stock int64, price float64, description string) (r string, err error)

	DeleteItem(ctx context.Context, id string) (err error)

	StartFlashSale(ctx context.Context, itemId string) (err error)

	StopFlashSale(ctx context.Context, itemId string) (err error)
}

type ItemSvrAddItemArgs struct {
	Name        string  `thrift:"name,1" frugal:"1,default,string" json:"name"`
	Stock       int64   `thrift:"stock,2" frugal:"2,default,i64" json:"stock"`
	Price       float64 `thrift:"price,3" frugal:"3,default,double" json:"price"`
	Description string  `thrift:"description,4" frugal:"4,default,string" json:"description"`
}

func NewItemSvrAddItemArgs() *ItemSvrAddItemArgs {
	return &ItemSvrAddItemArgs{}
}

func (p *ItemSvrAddItemArgs) InitDefault() {
}

func (p *ItemSvrAddItemArgs) GetName() (v string) {
	return p.Name
}

func (p *ItemSvrAddItemArgs) GetStock() (v int64) {
	return p.Stock
}

func (p *ItemSvrAddItemArgs) GetPrice() (v float64) {
	return p.Price
}

func (p *ItemSvrAddItemArgs) GetDescription() (v string) {
	return p.Description
}

func (p *ItemSvrAddItemArgs) SetName(val string) {
	p.Name = val
}

func (p *ItemSvrAddItemArgs) SetStock(val int64) {
	p.Stock = val
}

func (p *ItemSvrAddItemArgs) SetPrice(val float64) {
	p.Price = val
}

func (p *ItemSvrAddItemArgs) SetDescription(val string) {
	p.Description = val
}

func (p *ItemSvrAddItemArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemSvrAddItemArgs(%+v)", *p)
}

var fieldIDToName_ItemSvrAddItemArgs = map[int16]string{
	1: "name",
	2: "stock",
	3: "price",
	4: "description",
}

type ItemSvrAddItemResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewItemSvrAddItemResult() *ItemSvrAddItemResult {
	return &ItemSvrAddItemResult{}
}

func (p *ItemSvrAddItemResult) InitDefault() {
}

var ItemSvrAddItemResult_Success_DEFAULT string

func (p *ItemSvrAddItemResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return ItemSvrAddItemResult_Success_DEFAULT
	}
	return *p.Success
}

func (p *ItemSvrAddItemResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *ItemSvrAddItemResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ItemSvrAddItemResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemSvrAddItemResult(%+v)", *p)
}

var fieldIDToName_ItemSvrAddItemResult = map[int16]string{
	0: "success",
}

type ItemSvrDeleteItemArgs struct {
	ID string `thrift:"id,1" frugal:"1,default,string" json:"id"`
}

func NewItemSvrDeleteItemArgs() *ItemSvrDeleteItemArgs {
	return &ItemSvrDeleteItemArgs{}
}

func (p *ItemSvrDeleteItemArgs) InitDefault() {
}

func (p *ItemSvrDeleteItemArgs) GetID() (v string) {
	return p.ID
}

func (p *ItemSvrDeleteItemArgs) SetID(val string) {
	p.ID = val
}

func (p *ItemSvrDeleteItemArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemSvrDeleteItemArgs(%+v)", *p)
}

var fieldIDToName_ItemSvrDeleteItemArgs = map[int16]string{
	1: "id",
}

type ItemSvrDeleteItemResult struct {
}

func NewItemSvrDeleteItemResult() *ItemSvrDeleteItemResult {
	return &ItemSvrDeleteItemResult{}
}

func (p *ItemSvrDeleteItemResult) InitDefault() {
}

func (p *ItemSvrDeleteItemResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemSvrDeleteItemResult(%+v)", *p)
}

var fieldIDToName_ItemSvrDeleteItemResult = map[int16]string{}

type ItemSvrStartFlashSaleArgs struct {
	ItemId string `thrift:"itemId,1" frugal:"1,default,string" json:"itemId"`
}

func NewItemSvrStartFlashSaleArgs() *ItemSvrStartFlashSaleArgs {
	return &ItemSvrStartFlashSaleArgs{}
}

func (p *ItemSvrStartFlashSaleArgs) InitDefault() {
}

func (p *ItemSvrStartFlashSaleArgs) GetItemId() (v string) {
	return p.ItemId
}

func (p *ItemSvrStartFlashSaleArgs) SetItemId(val string) {
	p.ItemId = val
}

func (p *ItemSvrStartFlashSaleArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemSvrStartFlashSaleArgs(%+v)", *p)
}

var fieldIDToName_ItemSvrStartFlashSaleArgs = map[int16]string{
	1: "itemId",
}

type ItemSvrStartFlashSaleResult struct {
}

func NewItemSvrStartFlashSaleResult() *ItemSvrStartFlashSaleResult {
	return &ItemSvrStartFlashSaleResult{}
}

func (p *ItemSvrStartFlashSaleResult) InitDefault() {
}

func (p *ItemSvrStartFlashSaleResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemSvrStartFlashSaleResult(%+v)", *p)
}

var fieldIDToName_ItemSvrStartFlashSaleResult = map[int16]string{}

type ItemSvrStopFlashSaleArgs struct {
	ItemId string `thrift:"itemId,1" frugal:"1,default,string" json:"itemId"`
}

func NewItemSvrStopFlashSaleArgs() *ItemSvrStopFlashSaleArgs {
	return &ItemSvrStopFlashSaleArgs{}
}

func (p *ItemSvrStopFlashSaleArgs) InitDefault() {
}

func (p *ItemSvrStopFlashSaleArgs) GetItemId() (v string) {
	return p.ItemId
}

func (p *ItemSvrStopFlashSaleArgs) SetItemId(val string) {
	p.ItemId = val
}

func (p *ItemSvrStopFlashSaleArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemSvrStopFlashSaleArgs(%+v)", *p)
}

var fieldIDToName_ItemSvrStopFlashSaleArgs = map[int16]string{
	1: "itemId",
}

type ItemSvrStopFlashSaleResult struct {
}

func NewItemSvrStopFlashSaleResult() *ItemSvrStopFlashSaleResult {
	return &ItemSvrStopFlashSaleResult{}
}

func (p *ItemSvrStopFlashSaleResult) InitDefault() {
}

func (p *ItemSvrStopFlashSaleResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ItemSvrStopFlashSaleResult(%+v)", *p)
}

var fieldIDToName_ItemSvrStopFlashSaleResult = map[int16]string{}
