# 绑定所有网络接口
bind 0.0.0.0
# 设置访问密码（应与主节点保持一致）
requirepass root
# 设置连接主节点的密码
masterauth root
# 关键！指明自己的主节点是谁
replicaof redis-master 6379
# 开启AOF持久化
appendonly yes
# 设定内存上限及淘汰策略
maxmemory 256mb
maxmemory-policy allkeys-lru
