// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package usersvr

import (
	"context"
	"fmt"
)

type JWTToken struct {
	AccessToken  string `thrift:"accessToken,1,required" frugal:"1,required,string" json:"accessToken"`
	RefreshToken string `thrift:"refreshToken,2,required" frugal:"2,required,string" json:"refreshToken"`
}

func NewJWTToken() *JWTToken {
	return &JWTToken{}
}

func (p *JWTToken) InitDefault() {
}

func (p *JWTToken) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *JWTToken) GetRefreshToken() (v string) {
	return p.RefreshToken
}
func (p *JWTToken) SetAccessToken(val string) {
	p.AccessToken = val
}
func (p *JWTToken) SetRefreshToken(val string) {
	p.RefreshToken = val
}

func (p *JWTToken) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("JWTToken(%+v)", *p)
}

var fieldIDToName_JWTToken = map[int16]string{
	1: "accessToken",
	2: "refreshToken",
}

type UserSvr interface {
	RegisterUser(ctx context.Context, uid string, password string) (err error)

	Login(ctx context.Context, uid string, password string) (r *JWTToken, err error)

	Logout(ctx context.Context, accessToken string) (err error)

	RefreshAccessToken(ctx context.Context, refreshToken string) (r string, err error)
}

type UserSvrRegisterUserArgs struct {
	Uid      string `thrift:"uid,1" frugal:"1,default,string" json:"uid"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewUserSvrRegisterUserArgs() *UserSvrRegisterUserArgs {
	return &UserSvrRegisterUserArgs{}
}

func (p *UserSvrRegisterUserArgs) InitDefault() {
}

func (p *UserSvrRegisterUserArgs) GetUid() (v string) {
	return p.Uid
}

func (p *UserSvrRegisterUserArgs) GetPassword() (v string) {
	return p.Password
}
func (p *UserSvrRegisterUserArgs) SetUid(val string) {
	p.Uid = val
}
func (p *UserSvrRegisterUserArgs) SetPassword(val string) {
	p.Password = val
}

func (p *UserSvrRegisterUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrRegisterUserArgs(%+v)", *p)
}

var fieldIDToName_UserSvrRegisterUserArgs = map[int16]string{
	1: "uid",
	2: "password",
}

type UserSvrRegisterUserResult struct {
}

func NewUserSvrRegisterUserResult() *UserSvrRegisterUserResult {
	return &UserSvrRegisterUserResult{}
}

func (p *UserSvrRegisterUserResult) InitDefault() {
}

func (p *UserSvrRegisterUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrRegisterUserResult(%+v)", *p)
}

var fieldIDToName_UserSvrRegisterUserResult = map[int16]string{}

type UserSvrLoginArgs struct {
	Uid      string `thrift:"uid,1" frugal:"1,default,string" json:"uid"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewUserSvrLoginArgs() *UserSvrLoginArgs {
	return &UserSvrLoginArgs{}
}

func (p *UserSvrLoginArgs) InitDefault() {
}

func (p *UserSvrLoginArgs) GetUid() (v string) {
	return p.Uid
}

func (p *UserSvrLoginArgs) GetPassword() (v string) {
	return p.Password
}
func (p *UserSvrLoginArgs) SetUid(val string) {
	p.Uid = val
}
func (p *UserSvrLoginArgs) SetPassword(val string) {
	p.Password = val
}

func (p *UserSvrLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrLoginArgs(%+v)", *p)
}

var fieldIDToName_UserSvrLoginArgs = map[int16]string{
	1: "uid",
	2: "password",
}

type UserSvrLoginResult struct {
	Success *JWTToken `thrift:"success,0,optional" frugal:"0,optional,JWTToken" json:"success,omitempty"`
}

func NewUserSvrLoginResult() *UserSvrLoginResult {
	return &UserSvrLoginResult{}
}

func (p *UserSvrLoginResult) InitDefault() {
}

var UserSvrLoginResult_Success_DEFAULT *JWTToken

func (p *UserSvrLoginResult) GetSuccess() (v *JWTToken) {
	if !p.IsSetSuccess() {
		return UserSvrLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserSvrLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*JWTToken)
}

func (p *UserSvrLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserSvrLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrLoginResult(%+v)", *p)
}

var fieldIDToName_UserSvrLoginResult = map[int16]string{
	0: "success",
}

type UserSvrLogoutArgs struct {
	AccessToken string `thrift:"accessToken,1" frugal:"1,default,string" json:"accessToken"`
}

func NewUserSvrLogoutArgs() *UserSvrLogoutArgs {
	return &UserSvrLogoutArgs{}
}

func (p *UserSvrLogoutArgs) InitDefault() {
}

func (p *UserSvrLogoutArgs) GetAccessToken() (v string) {
	return p.AccessToken
}
func (p *UserSvrLogoutArgs) SetAccessToken(val string) {
	p.AccessToken = val
}

func (p *UserSvrLogoutArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrLogoutArgs(%+v)", *p)
}

var fieldIDToName_UserSvrLogoutArgs = map[int16]string{
	1: "accessToken",
}

type UserSvrLogoutResult struct {
}

func NewUserSvrLogoutResult() *UserSvrLogoutResult {
	return &UserSvrLogoutResult{}
}

func (p *UserSvrLogoutResult) InitDefault() {
}

func (p *UserSvrLogoutResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrLogoutResult(%+v)", *p)
}

var fieldIDToName_UserSvrLogoutResult = map[int16]string{}

type UserSvrRefreshAccessTokenArgs struct {
	RefreshToken string `thrift:"refreshToken,1" frugal:"1,default,string" json:"refreshToken"`
}

func NewUserSvrRefreshAccessTokenArgs() *UserSvrRefreshAccessTokenArgs {
	return &UserSvrRefreshAccessTokenArgs{}
}

func (p *UserSvrRefreshAccessTokenArgs) InitDefault() {
}

func (p *UserSvrRefreshAccessTokenArgs) GetRefreshToken() (v string) {
	return p.RefreshToken
}
func (p *UserSvrRefreshAccessTokenArgs) SetRefreshToken(val string) {
	p.RefreshToken = val
}

func (p *UserSvrRefreshAccessTokenArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrRefreshAccessTokenArgs(%+v)", *p)
}

var fieldIDToName_UserSvrRefreshAccessTokenArgs = map[int16]string{
	1: "refreshToken",
}

type UserSvrRefreshAccessTokenResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewUserSvrRefreshAccessTokenResult() *UserSvrRefreshAccessTokenResult {
	return &UserSvrRefreshAccessTokenResult{}
}

func (p *UserSvrRefreshAccessTokenResult) InitDefault() {
}

var UserSvrRefreshAccessTokenResult_Success_DEFAULT string

func (p *UserSvrRefreshAccessTokenResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return UserSvrRefreshAccessTokenResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserSvrRefreshAccessTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *UserSvrRefreshAccessTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserSvrRefreshAccessTokenResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrRefreshAccessTokenResult(%+v)", *p)
}

var fieldIDToName_UserSvrRefreshAccessTokenResult = map[int16]string{
	0: "success",
}
