// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package ordersvr

import (
	"context"
	"fmt"
)

type OrderStatus int64

const (
	OrderStatus_UNPAID    OrderStatus = 1
	OrderStatus_PAID      OrderStatus = 2
	OrderStatus_CANCELLED OrderStatus = 3
)

func (p OrderStatus) String() string {
	switch p {
	case OrderStatus_UNPAID:
		return "UNPAID"
	case OrderStatus_PAID:
		return "PAID"
	case OrderStatus_CANCELLED:
		return "CANCELLED"
	}
	return "<UNSET>"
}

func OrderStatusFromString(s string) (OrderStatus, error) {
	switch s {
	case "UNPAID":
		return OrderStatus_UNPAID, nil
	case "PAID":
		return OrderStatus_PAID, nil
	case "CANCELLED":
		return OrderStatus_CANCELLED, nil
	}
	return OrderStatus(0), fmt.Errorf("not a valid OrderStatus string")
}

func OrderStatusPtr(v OrderStatus) *OrderStatus { return &v }

type OrderInfo struct {
	OrderId    string      `thrift:"orderId,1,required" frugal:"1,required,string" json:"orderId"`
	UserId     string      `thrift:"userId,2,required" frugal:"2,required,string" json:"userId"`
	ItemId     string      `thrift:"itemId,3,required" frugal:"3,required,string" json:"itemId"`
	Price      float64     `thrift:"price,4,required" frugal:"4,required,double" json:"price"`
	Status     OrderStatus `thrift:"status,5,required" frugal:"5,required,OrderStatus" json:"status"`
	CreateTime string      `thrift:"createTime,6,required" frugal:"6,required,string" json:"createTime"`
}

func NewOrderInfo() *OrderInfo {
	return &OrderInfo{}
}

func (p *OrderInfo) InitDefault() {
}

func (p *OrderInfo) GetOrderId() (v string) {
	return p.OrderId
}

func (p *OrderInfo) GetUserId() (v string) {
	return p.UserId
}

func (p *OrderInfo) GetItemId() (v string) {
	return p.ItemId
}

func (p *OrderInfo) GetPrice() (v float64) {
	return p.Price
}

func (p *OrderInfo) GetStatus() (v OrderStatus) {
	return p.Status
}

func (p *OrderInfo) GetCreateTime() (v string) {
	return p.CreateTime
}

func (p *OrderInfo) SetOrderId(val string) {
	p.OrderId = val
}

func (p *OrderInfo) SetUserId(val string) {
	p.UserId = val
}

func (p *OrderInfo) SetItemId(val string) {
	p.ItemId = val
}

func (p *OrderInfo) SetPrice(val float64) {
	p.Price = val
}

func (p *OrderInfo) SetStatus(val OrderStatus) {
	p.Status = val
}

func (p *OrderInfo) SetCreateTime(val string) {
	p.CreateTime = val
}

func (p *OrderInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderInfo(%+v)", *p)
}

var fieldIDToName_OrderInfo = map[int16]string{
	1: "orderId",
	2: "userId",
	3: "itemId",
	4: "price",
	5: "status",
	6: "createTime",
}

type OrderSvr interface {
	CreateOrder(ctx context.Context, userId string, itemId string, price float64) (r string, err error)

	QueryPaidOrders(ctx context.Context, userId string) (r []*OrderInfo, err error)

	QueryUnpaidOrders(ctx context.Context, userId string) (r []*OrderInfo, err error)

	QueryCancelledOrders(ctx context.Context, userId string) (r []*OrderInfo, err error)
}

type OrderSvrCreateOrderArgs struct {
	UserId string  `thrift:"userId,1" frugal:"1,default,string" json:"userId"`
	ItemId string  `thrift:"itemId,2" frugal:"2,default,string" json:"itemId"`
	Price  float64 `thrift:"price,3" frugal:"3,default,double" json:"price"`
}

func NewOrderSvrCreateOrderArgs() *OrderSvrCreateOrderArgs {
	return &OrderSvrCreateOrderArgs{}
}

func (p *OrderSvrCreateOrderArgs) InitDefault() {
}

func (p *OrderSvrCreateOrderArgs) GetUserId() (v string) {
	return p.UserId
}

func (p *OrderSvrCreateOrderArgs) GetItemId() (v string) {
	return p.ItemId
}

func (p *OrderSvrCreateOrderArgs) GetPrice() (v float64) {
	return p.Price
}

func (p *OrderSvrCreateOrderArgs) SetUserId(val string) {
	p.UserId = val
}

func (p *OrderSvrCreateOrderArgs) SetItemId(val string) {
	p.ItemId = val
}

func (p *OrderSvrCreateOrderArgs) SetPrice(val float64) {
	p.Price = val
}

func (p *OrderSvrCreateOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderSvrCreateOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderSvrCreateOrderArgs = map[int16]string{
	1: "userId",
	2: "itemId",
	3: "price",
}

type OrderSvrCreateOrderResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewOrderSvrCreateOrderResult() *OrderSvrCreateOrderResult {
	return &OrderSvrCreateOrderResult{}
}

func (p *OrderSvrCreateOrderResult) InitDefault() {
}

var OrderSvrCreateOrderResult_Success_DEFAULT string

func (p *OrderSvrCreateOrderResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return OrderSvrCreateOrderResult_Success_DEFAULT
	}
	return *p.Success
}

func (p *OrderSvrCreateOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *OrderSvrCreateOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderSvrCreateOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderSvrCreateOrderResult(%+v)", *p)
}

var fieldIDToName_OrderSvrCreateOrderResult = map[int16]string{
	0: "success",
}

type OrderSvrQueryPaidOrdersArgs struct {
	UserId string `thrift:"userId,1" frugal:"1,default,string" json:"userId"`
}

func NewOrderSvrQueryPaidOrdersArgs() *OrderSvrQueryPaidOrdersArgs {
	return &OrderSvrQueryPaidOrdersArgs{}
}

func (p *OrderSvrQueryPaidOrdersArgs) InitDefault() {
}

func (p *OrderSvrQueryPaidOrdersArgs) GetUserId() (v string) {
	return p.UserId
}

func (p *OrderSvrQueryPaidOrdersArgs) SetUserId(val string) {
	p.UserId = val
}

func (p *OrderSvrQueryPaidOrdersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderSvrQueryPaidOrdersArgs(%+v)", *p)
}

var fieldIDToName_OrderSvrQueryPaidOrdersArgs = map[int16]string{
	1: "userId",
}

type OrderSvrQueryPaidOrdersResult struct {
	Success []*OrderInfo `thrift:"success,0,optional" frugal:"0,optional,list<OrderInfo>" json:"success,omitempty"`
}

func NewOrderSvrQueryPaidOrdersResult() *OrderSvrQueryPaidOrdersResult {
	return &OrderSvrQueryPaidOrdersResult{}
}

func (p *OrderSvrQueryPaidOrdersResult) InitDefault() {
}

var OrderSvrQueryPaidOrdersResult_Success_DEFAULT []*OrderInfo

func (p *OrderSvrQueryPaidOrdersResult) GetSuccess() (v []*OrderInfo) {
	if !p.IsSetSuccess() {
		return OrderSvrQueryPaidOrdersResult_Success_DEFAULT
	}
	return p.Success
}

func (p *OrderSvrQueryPaidOrdersResult) SetSuccess(x interface{}) {
	p.Success = x.([]*OrderInfo)
}

func (p *OrderSvrQueryPaidOrdersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderSvrQueryPaidOrdersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderSvrQueryPaidOrdersResult(%+v)", *p)
}

var fieldIDToName_OrderSvrQueryPaidOrdersResult = map[int16]string{
	0: "success",
}

type OrderSvrQueryUnpaidOrdersArgs struct {
	UserId string `thrift:"userId,1" frugal:"1,default,string" json:"userId"`
}

func NewOrderSvrQueryUnpaidOrdersArgs() *OrderSvrQueryUnpaidOrdersArgs {
	return &OrderSvrQueryUnpaidOrdersArgs{}
}

func (p *OrderSvrQueryUnpaidOrdersArgs) InitDefault() {
}

func (p *OrderSvrQueryUnpaidOrdersArgs) GetUserId() (v string) {
	return p.UserId
}

func (p *OrderSvrQueryUnpaidOrdersArgs) SetUserId(val string) {
	p.UserId = val
}

func (p *OrderSvrQueryUnpaidOrdersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderSvrQueryUnpaidOrdersArgs(%+v)", *p)
}

var fieldIDToName_OrderSvrQueryUnpaidOrdersArgs = map[int16]string{
	1: "userId",
}

type OrderSvrQueryUnpaidOrdersResult struct {
	Success []*OrderInfo `thrift:"success,0,optional" frugal:"0,optional,list<OrderInfo>" json:"success,omitempty"`
}

func NewOrderSvrQueryUnpaidOrdersResult() *OrderSvrQueryUnpaidOrdersResult {
	return &OrderSvrQueryUnpaidOrdersResult{}
}

func (p *OrderSvrQueryUnpaidOrdersResult) InitDefault() {
}

var OrderSvrQueryUnpaidOrdersResult_Success_DEFAULT []*OrderInfo

func (p *OrderSvrQueryUnpaidOrdersResult) GetSuccess() (v []*OrderInfo) {
	if !p.IsSetSuccess() {
		return OrderSvrQueryUnpaidOrdersResult_Success_DEFAULT
	}
	return p.Success
}

func (p *OrderSvrQueryUnpaidOrdersResult) SetSuccess(x interface{}) {
	p.Success = x.([]*OrderInfo)
}

func (p *OrderSvrQueryUnpaidOrdersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderSvrQueryUnpaidOrdersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderSvrQueryUnpaidOrdersResult(%+v)", *p)
}

var fieldIDToName_OrderSvrQueryUnpaidOrdersResult = map[int16]string{
	0: "success",
}

type OrderSvrQueryCancelledOrdersArgs struct {
	UserId string `thrift:"userId,1" frugal:"1,default,string" json:"userId"`
}

func NewOrderSvrQueryCancelledOrdersArgs() *OrderSvrQueryCancelledOrdersArgs {
	return &OrderSvrQueryCancelledOrdersArgs{}
}

func (p *OrderSvrQueryCancelledOrdersArgs) InitDefault() {
}

func (p *OrderSvrQueryCancelledOrdersArgs) GetUserId() (v string) {
	return p.UserId
}

func (p *OrderSvrQueryCancelledOrdersArgs) SetUserId(val string) {
	p.UserId = val
}

func (p *OrderSvrQueryCancelledOrdersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderSvrQueryCancelledOrdersArgs(%+v)", *p)
}

var fieldIDToName_OrderSvrQueryCancelledOrdersArgs = map[int16]string{
	1: "userId",
}

type OrderSvrQueryCancelledOrdersResult struct {
	Success []*OrderInfo `thrift:"success,0,optional" frugal:"0,optional,list<OrderInfo>" json:"success,omitempty"`
}

func NewOrderSvrQueryCancelledOrdersResult() *OrderSvrQueryCancelledOrdersResult {
	return &OrderSvrQueryCancelledOrdersResult{}
}

func (p *OrderSvrQueryCancelledOrdersResult) InitDefault() {
}

var OrderSvrQueryCancelledOrdersResult_Success_DEFAULT []*OrderInfo

func (p *OrderSvrQueryCancelledOrdersResult) GetSuccess() (v []*OrderInfo) {
	if !p.IsSetSuccess() {
		return OrderSvrQueryCancelledOrdersResult_Success_DEFAULT
	}
	return p.Success
}

func (p *OrderSvrQueryCancelledOrdersResult) SetSuccess(x interface{}) {
	p.Success = x.([]*OrderInfo)
}

func (p *OrderSvrQueryCancelledOrdersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderSvrQueryCancelledOrdersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderSvrQueryCancelledOrdersResult(%+v)", *p)
}

var fieldIDToName_OrderSvrQueryCancelledOrdersResult = map[int16]string{
	0: "success",
}
